services:
  postgres:
    image: postgres:15
    container_name: bank-app-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank-app-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank_app_network

volumes:
  postgres_data:

networks:
  car_shop_network:
    driver: bridge
